### ISSUE TITLE
about the training loss become nan

### ISSUE THREAD

**Issue by ywher** [rayguan97/GANav-offroad#14]
hi，nice work. But I meet some problems.
When I use the default config file and train the network on resllis3D, I found the loss became nan during training.
Has anyone else had a similar problem?
The first few records of the training are shown below：
2022-07-26 11:14:00,126 - mmseg - INFO - Iter [50/160000]       lr: 9.997e-03, eta: 11:13:45, time: 0.253, data_time: 0.010, memory: 17373, decode.loss_seg: 10.1304, decode.acc_seg: 21.6483, aux.loss_seg: 0.6783, aux.acc_seg: 21.7035, loss: 10.8088
2022-07-26 11:14:07,372 - mmseg - INFO - Iter [100/160000]      lr: 9.994e-03, eta: 8:49:53, time: 0.145, data_time: 0.001, memory: 17373, decode.loss_seg: nan, decode.acc_seg: 23.8205, aux.loss_seg: nan, aux.acc_seg: 31.7386, loss: nan
2022-07-26 11:14:14,590 - mmseg - INFO - Iter [150/160000]      lr: 9.992e-03, eta: 8:01:19, time: 0.144, data_time: 0.001, memory: 17373, decode.loss_seg: nan, decode.acc_seg: 24.1812, aux.loss_seg: nan, aux.acc_seg: 24.1812, loss: nan
2022-07-26 11:14:21,808 - mmseg - INFO - Iter [200/160000]      lr: 9.989e-03, eta: 7:37:00, time: 0.144, data_time: 0.001, memory: 17373, decode.loss_seg: nan, decode.acc_seg: 28.6286, aux.loss_seg: nan, aux.acc_seg: 28.6286, loss: nan
2022-07-26 11:14:29,039 - mmseg - INFO - Iter [250/160000]      lr: 9.986e-03, eta: 7:22:29, time: 0.145, data_time: 0.001, memory: 17373, decode.loss_seg: nan, decode.acc_seg: 24.6320, aux.loss_seg: nan, aux.acc_seg: 24.6320, loss: nan
2022-07-26 11:14:36,279 - mmseg - INFO - Iter [300/160000]      lr: 9.983e-03, eta: 7:12:52, time: 0.145, data_time: 0.001, memory: 17373, decode.loss_seg: nan, decode.acc_seg: 22.7228, aux.loss_seg: nan, aux.acc_seg: 22.7228, loss: nan
2022-07-26 11:14:43,525 - mmseg - INFO - Iter [350/160000]      lr: 9.981e-03, eta: 7:05:59, time: 0.145, data_time: 0.001, memory: 17373, decode.loss_seg: nan, decode.acc_seg: 24.7156, aux.loss_seg: nan, aux.acc_seg: 24.7156, loss: nan
2022-07-26 11:14:50,798 - mmseg - INFO - Iter [400/160000]      lr: 9.978e-03, eta: 7:00:59, time: 0.145, data_time: 0.001, memory: 17373, decode.loss_seg: nan, decode.acc_seg: 25.7715, aux.loss_seg: nan, aux.acc_seg: 25.7715, loss: nan

**Comment by ywher** [comment]
I found that it may be because the current code is single-card training, and the samples_per_gpu in rellis_group6.py needs to be changed to 2. Additionally, in the paper the authors say "In the ablations and comparisons, for fairness, we benchmark all our models at 240K iterations", but iterations are set as 160K in the ganav_group6_rellis.py. This is another a small question.

**Comment by ywher** [comment]
NAN again, after I changed the batch size from 1 to 2.
2022-07-26 11:33:46,558 - mmseg - INFO - Iter [50/240000]	lr: 9.998e-03, eta: 1 day, 0:43:21, time: 0.371, data_time: 0.005, memory: 17671, decode.loss_seg: 36.8659, decode.acc_seg: 19.6090, aux.loss_seg: 0.6523, aux.acc_seg: 28.1575, loss: 37.5183
2022-07-26 11:34:00,031 - mmseg - INFO - Iter [100/240000]	lr: 9.996e-03, eta: 21:20:13, time: 0.269, data_time: 0.002, memory: 17671, decode.loss_seg: 12.2197, decode.acc_seg: 31.8857, aux.loss_seg: 0.6118, aux.acc_seg: 34.3522, loss: 12.8315
2022-07-26 11:34:13,954 - mmseg - INFO - Iter [150/240000]	lr: 9.994e-03, eta: 20:24:18, time: 0.278, data_time: 0.002, memory: 17671, decode.loss_seg: 9.7978, decode.acc_seg: 29.3605, aux.loss_seg: 0.6117, aux.acc_seg: 34.8084, loss: 10.4095
2022-07-26 11:34:29,598 - mmseg - INFO - Iter [200/240000]	lr: 9.993e-03, eta: 20:30:37, time: 0.313, data_time: 0.002, memory: 17671, decode.loss_seg: 6.7851, decode.acc_seg: 28.4055, aux.loss_seg: 0.6025, aux.acc_seg: 32.5100, loss: 7.3876
2022-07-26 11:34:47,572 - mmseg - INFO - Iter [250/240000]	lr: 9.991e-03, eta: 21:11:34, time: 0.359, data_time: 0.002, memory: 17671, decode.loss_seg: 6.1998, decode.acc_seg: 28.8685, aux.loss_seg: 0.6131, aux.acc_seg: 37.6449, loss: 6.8129
2022-07-26 11:35:05,571 - mmseg - INFO - Iter [300/240000]	lr: 9.989e-03, eta: 21:39:06, time: 0.360, data_time: 0.002, memory: 17671, decode.loss_seg: 9.3100, decode.acc_seg: 30.8935, aux.loss_seg: 0.5739, aux.acc_seg: 40.4643, loss: 9.8840
2022-07-26 11:35:23,543 - mmseg - INFO - Iter [350/240000]	lr: 9.987e-03, eta: 21:58:23, time: 0.359, data_time: 0.002, memory: 17671, decode.loss_seg: 12.8057, decode.acc_seg: 26.7339, aux.loss_seg: 0.5988, aux.acc_seg: 36.8817, loss: 13.4045
2022-07-26 11:35:41,434 - mmseg - INFO - Iter [400/240000]	lr: 9.985e-03, eta: 22:11:56, time: 0.358, data_time: 0.002, memory: 17671, decode.loss_seg: 33.5382, decode.acc_seg: 39.3062, aux.loss_seg: 0.6051, aux.acc_seg: 43.8996, loss: 34.1433
2022-07-26 11:35:59,405 - mmseg - INFO - Iter [450/240000]	lr: 9.983e-03, eta: 22:23:08, time: 0.359, data_time: 0.002, memory: 17671, decode.loss_seg: 16.7517, decode.acc_seg: 24.2791, aux.loss_seg: 0.5761, aux.acc_seg: 41.6234, loss: 17.3278
2022-07-26 11:36:17,406 - mmseg - INFO - Iter [500/240000]	lr: 9.981e-03, eta: 22:32:17, time: 0.360, data_time: 0.002, memory: 17671, decode.loss_seg: 10.3142, decode.acc_seg: 30.3935, aux.loss_seg: 0.5899, aux.acc_seg: 39.1280, loss: 10.9040
2022-07-26 11:36:35,445 - mmseg - INFO - Iter [550/240000]	lr: 9.980e-03, eta: 22:39:59, time: 0.361, data_time: 0.002, memory: 17671, decode.loss_seg: nan, decode.acc_seg: 28.4942, aux.loss_seg: nan, aux.acc_seg: 39.3411, loss: nan
2022-07-26 11:36:51,019 - mmseg - INFO - Iter [600/240000]	lr: 9.978e-03, eta: 22:29:57, time: 0.311, data_time: 0.002, memory: 17671, decode.loss_seg: nan, decode.acc_seg: 20.4404, aux.loss_seg: nan, aux.acc_seg: 20.4404, loss: nan
2022-07-26 11:37:06,632 - mmseg - INFO - Iter [650/240000]	lr: 9.976e-03, eta: 22:21:40, time: 0.312, data_time: 0.002, memory: 17671, decode.loss_seg: nan, decode.acc_seg: 28.1801, aux.loss_seg: nan, aux.acc_seg: 28.1801, loss: nan
2022-07-26 11:37:22,231 - mmseg - INFO - Iter [700/240000]	lr: 9.974e-03, eta: 22:14:27, time: 0.312, data_time: 0.002, memory: 17671, decode.loss_seg: nan, decode.acc_seg: 26.7899, aux.loss_seg: nan, aux.acc_seg: 26.7899, loss: nan
2022-07-26 11:37:37,824 - mmseg - INFO - Iter [750/240000]	lr: 9.972e-03, eta: 22:08:08, time: 0.312, data_time: 0.002, memory: 17671, decode.loss_seg: nan, decode.acc_seg: 25.6708, aux.loss_seg: nan, aux.acc_seg: 25.6708, loss: nan
2022-07-26 11:37:53,442 - mmseg - INFO - Iter [800/240000]	lr: 9.970e-03, eta: 22:02:41, time: 0.312, data_time: 0.002, memory: 17671, decode.loss_seg: nan, decode.acc_seg: 25.0798, aux.loss_seg: nan, aux.acc_seg: 25.0798, loss: nan
2022-07-26 11:38:12,257 - mmseg - INFO - Iter [850/240000]	lr: 9.968e-03, eta: 22:12:51, time: 0.376, data_time: 0.002, memory: 17671, decode.loss_seg: nan, decode.acc_seg: 28.5087, aux.loss_seg: nan, aux.acc_seg: 28.5087, loss: nan

**Comment by rayguan97** [comment]
Have you tried to adjust/lower the learning rate accordingly? I have seen this issue but have it fixed after adjusting the learning rate. 

You can adjust the number of iterations pretty easily and we only show one example of the config file we have, which has 160k iterations.

**Comment by ywher** [comment]
> Have you tried to adjust/lower the learning rate accordingly? I have seen this issue but have it fixed after adjusting the learning rate.
> 
> You can adjust the number of iterations pretty easily and we only show one example of the config file we have, which has 160k iterations.

Thanks, I have tried to lower the learning rate from 0.01 to 0.005 and it works.
But I meet another problem. I set training iterations to 240k and eval moedl each 24k.(160k and 16k in default)
After the evaluation, the training peocess brke down.

The error messages are:
2022-07-26 13:37:16,619 - mmseg - INFO - 
+------------+-------+-------+
| Class      | IoU   | Acc   |
+------------+-------+-------+
| background | 81.89 | 98.45 |
| L1         | 5.3   | 90.69 |
| L2         | 60.13 | 71.73 |
| L3         | 0.24  | 0.24  |
| non-Nav    | 36.88 | 45.8  |
| obstacle   | 57.56 | 72.78 |
+------------+-------+-------+
2022-07-26 13:37:16,620 - mmseg - INFO - Summary:
2022-07-26 13:37:16,620 - mmseg - INFO - 
+--------+-------+-------+-------+
| Scope  | mIoU  | mAcc  | aAcc  |
+--------+-------+-------+-------+
| global | 40.33 | 63.28 | 70.93 |
+--------+-------+-------+-------+
2022-07-26 13:37:16,712 - mmseg - INFO - Exp name: ganav_group6_rellis.py
Traceback (most recent call last):
  File "./tools/train.py", line 179, in <module>
    main()
  File "./tools/train.py", line 175, in main
    meta=meta)
  File "/Data/xjy/yueye_project/GANav-offroad-main/mmseg/apis/train.py", line 118, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/cyber/anaconda3/envs/ganav/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/cyber/anaconda3/envs/ganav/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 67, in train
    self.call_hook('after_train_iter')
  File "/home/cyber/anaconda3/envs/ganav/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/cyber/anaconda3/envs/ganav/lib/python3.7/site-packages/mmcv/runner/hooks/logger/base.py", line 152, in after_train_iter
    self.log(runner)
  File "/home/cyber/anaconda3/envs/ganav/lib/python3.7/site-packages/mmcv/runner/hooks/logger/text.py", line 234, in log
    self._log_info(log_dict, runner)
  File "/home/cyber/anaconda3/envs/ganav/lib/python3.7/site-packages/mmcv/runner/hooks/logger/text.py", line 153, in _log_info
    log_str += f'time: {log_dict["time"]:.3f}, ' \
KeyError: 'data_time'

**Comment by ywher** [comment]
I have fixed this problem. It may because the version of mmcv. I set the environment through:
conda install pytorch=1.10.0 torchvision cudatoolkit=11.3 -c pytorch
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html
You should modify the code in line 112 in mmseg/apis/train.py
from  runner.register_hook(eval_hook(val_dataloader, **eval_cfg)) 
to  runner.register_hook(eval_hook(val_dataloader, **eval_cfg), priority='LOW')

**Comment by rayguan97** [comment]
It’s possible that the MMCV (1.3.16) version do not need that flag, which I used. I’ll update that in the document and check backward compatibility for adding that flag. Thanks for the pointer!
