### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by sidharthnp** [rayguan97/GANav-offroad#27]
Even after installing mmcv-full with the 1.3.16 version the error persists.
I created the environment again, tried changing the version of the modules,but still the error is coming. Can u suggest a fix for the same.

(ganavsegmentation) C:\Users\HP\GANav-offroad>python ./tools/test.py ./trained_models/rugd_group6/ganav_rellis_6.py
C:\Users\HP\anaconda3\envs\ganavsegmentation\lib\site-packages\mmcv\cnn\bricks\transformer.py:28: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module.
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Traceback (most recent call last):
  File "./tools/test.py", line 18, in <module>
    from mmseg.apis import multi_gpu_test, single_gpu_test
  File "c:\users\hp\ganav-offroad\mmseg\apis\__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "c:\users\hp\ganav-offroad\mmseg\apis\inference.py", line 9, in <module>
    from mmseg.models import build_segmentor
  File "c:\users\hp\ganav-offroad\mmseg\models\__init__.py", line 5, in <module>
    from .decode_heads import *  # noqa: F401,F403
  File "c:\users\hp\ganav-offroad\mmseg\models\decode_heads\__init__.py", line 1, in <module>
    from .fcn_head import FCNHead
  File "c:\users\hp\ganav-offroad\mmseg\models\decode_heads\fcn_head.py", line 7, in <module>
    from .decode_head import BaseDecodeHead
  File "c:\users\hp\ganav-offroad\mmseg\models\decode_heads\decode_head.py", line 11, in <module>
    from ..losses import accuracy
  File "c:\users\hp\ganav-offroad\mmseg\models\losses\__init__.py", line 6, in <module>
    from .focal_loss import FocalLoss
  File "c:\users\hp\ganav-offroad\mmseg\models\losses\focal_loss.py", line 6, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "C:\Users\HP\anaconda3\envs\ganavsegmentation\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "C:\Users\HP\anaconda3\envs\ganavsegmentation\lib\site-packages\mmcv\ops\assign_score_withk.py", line 6, in <module>
    '_ext', ['assign_score_withk_forward', 'assign_score_withk_backward'])
  File "C:\Users\HP\anaconda3\envs\ganavsegmentation\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\HP\anaconda3\envs\ganavsegmentation\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

**Comment by rayguan97** [comment]
I have not seen similar issues before. Maybe you can look it up on google -- I found this issue and hope you can find solution here: https://github.com/open-mmlab/mmdetection/issues/3271

**Comment by sdj54837** [comment]
same problem，are you sloved it?

**Comment by rayguan97** [comment]
I don't have similar issue. Which mmcv version have you tried?

**Comment by rayguan97** [comment]
Closing due to stale. Please reopen if you have more questions.
